name: quantpilot

services:
  quantpilot:
    image: ghcr.io/charles-0509/quantpilot:latest
    build: .
    container_name: quantpilot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "0.0.0.0:10000:10000"
    restart: unless-stopped
